# Generated by Django 5.2.8 on 2025-12-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('density_g_per_cm3', models.FloatField(blank=True, help_text='g/cm^3', null=True)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.technology')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounts.material')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tier')),
            ],
            options={
                'unique_together': {('material', 'tier')},
            },
        ),
    ]
