# Generated by Django 5.2.6 on 2025-12-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technology_tier_material_materialprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hex', models.CharField(help_text='#RRGGBB', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedSTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/stls/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('volume_cm3', models.FloatField(blank=True, null=True)),
                ('weight_grams', models.FloatField(blank=True, null=True)),
                ('price_per_gram', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.color')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.material')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technology')),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tier')),
            ],
        ),
    ]
